apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wq022mgeu-python 
  janus-idp.io/tekton: wq022mgeu-python
  backstage.io/kubernetes-id: wq022mgeu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wq022mgeu-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml